### PR TITLE
Check Docker Compose version prior starting

### LINKED ISSUE #319: Check compose version on startup
### Problem

Currently if the user has docker-compose v1, instead of docker compose v2 installed they will experience a failure to start and a loop of errors similar to
```Waiting for the containers at 127.0.0.1:5600, retrying in 0.1 seconds...
Error: connect ECONNREFUSED 127.0.0.1:5600
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5600
}
```

This can make it difficult for users to debug and fix the issue.

### Solution

Add a check of the available docker compose version before starting

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by konstantinabl**
**Description**:
This PR adds check before starting if docker compose version is the right one.

**Related issue(s)**:

Fixes #319 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)
- [x] Tested with v1 docker compose on Linux
- [x] Tested with v2 < 2.12.2 docker compose on Linux
- [x] Test with v1 docker compose on Windows
- [x] Tested on Mac

### CODE REVIEW

File: src/helpers/dockerCheck.js [hunk 1]
```diff
@@ -76,4 +78,21 @@ module.exports = class DockerCheck {
...
+    // Exit code is 127 when no docker installation is found
+    if (resultFirstCommand.code === 127 && resultSecondCommand.code === 127) {
+        console.error('Seems like you do not have docker compose installed');
+    } else {
+      const version = resultFirstCommand.stdout ? resultFirstCommand.stdout : resultSecondCommand.stdout
+      if (semver.lt(version, '2.12.2')) {
+        console.error("You are using docker compose version prior to 2.12.2, please upgrade");
+      }
+    }
+  }
```
Comment (natanasow) [inline src/helpers/dockerCheck.js:97]: IMO, inversing the logic is the better approach in that case. We have requirements that the end-user has to satisfy. We don't care if is it using an old version of `docker compose` or didn't have `docker compose` at all.
```typescript
  static async checkDockerComposeVersion() {
    console.log('Checking docker compose version...');
    
    const dockerComposeVersion = await shell.exec(`docker compose version --short`, {silent:true});
    if (dockerComposeVersion.code === "<success_code>" && semver.gte(dockerComposeVersion?.stdout, '2.12.2')) {
      // seems good
      return true;
    }

    console.error('The hedera-local-node package requires docker compose >= 2.12.2');
  }
  ```

That's not a change request, just my thoughts. Aside from that, the PR LGTM :upside_down_face:  Approved. :confetti_ball:

**Review by natanasow — APPROVED** [review]
LGTM, there is a nit that's optional
